AllCops:
  Exclude:
    - 'coverage/**/*'
    - 'pkg/**/*'
    - 'test/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  NewCops: enable
  TargetRubyVersion: 2.5

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Naming/RescuedExceptionsVariableName:
  PreferredName: error
