AllCops:
  Exclude:
    - 'coverage/**/*'
    - 'pkg/**/*'
    - 'test/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  NewCops: enable
  TargetRubyVersion: 3.2

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Naming/BlockForwarding:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Style/ArgumentsForwarding:
  Enabled: false
